name: Fast Policy CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  policy:
    uses: sableos-project/.github/.github/workflows/reusable-fast-policy.yml@42f7b2b08a5991980609ca178fb116bc8484f944
